# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- develop-Yolanda
 
pool:
  vmImage: ubuntu-latest
  name: Default
  demands:
  - agent.name -equals AgenteFrontendYolanda
 
stages:
- stage: Preparation
  jobs:
  - job: PreparationJob
    steps:
    - script: echo Preparation!
    
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm install -g @angular/cli
        npm install -g firebase-tools
        ng build --prod
        firebase deploy --token $(FIREBASE_TOKEN)
      displayName: 'npm install and build'
 
- stage: Sonarqube
  jobs:
  - job: SonarqubeJob
    steps:
    - checkout: none
    - script: sonar-scanner.bat -D"sonar.projectKey=ProyectoIntegrado_Frontend" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.token=$(SQ_TOKEN)"
    - script: echo Sonarqube ok!